#!/bin/sh
#
# Copyright 2026 Kwezal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# Usage: build_palette csv_file output_dir palette_name palette_short_name palette_class_name palette_url
build_palette() {
  csv_file=$1
  output_dir=$2
  palette_name=$3
  palette_short_name=$4
  palette_class_name=$5
  palette_url=$6

  mkdir -p "$output_dir"

  css_content=''
  dart_content=''
  gpl_content=''
  scss_content=''
  swift_content=''
  xml_content=''

  row=0
  prev_hue=''
  while IFS=, read -r hue shade hex || [ -n "$hue" ]; do
    if [ "$row" -eq 0 ]; then
      row=1
      continue
    fi

    separator="\n"
    if [ "$row" -eq 1 ]; then
      row=2
      separator=''
    fi

    if [ "$hue" != "$prev_hue" ]; then
      hue_capitalized=$(awk -v s="$hue" 'BEGIN{print toupper(substr(s,1,1)) substr(s,2)}')
      prev_hue="$hue"
    fi

    if [ -n "$shade" ]; then
      id_capitalized="$hue_capitalized $shade"
      id_dash="$hue-$shade"
      id_lower="$hue$shade"
    else
      id_capitalized="$hue_capitalized"
      id_dash="$hue"
      id_lower="$hue"
    fi

    hex_int=$(printf "%d" "0x$hex")
    red=$((hex_int >> 16))
    green=$(((hex_int & 0xFF00) >> 8))
    blue=$((hex_int & 0xFF))

    css_content="$css_content$separator    --$id_dash: #$hex;"
    dart_content="$dart_content$separator  static const $id_lower = Color(0x$hex);"
    gpl_content="$gpl_content$separator$(printf '%3s' "$red") $(printf '%3s' "$green") $(printf '%3s' "$blue") $id_capitalized"
    scss_content="$scss_content$separator\$$id_dash: #$hex;"
    swift_content="$swift_content$separator    static let $id_lower = Color(red: $red.0 / 255.0, green: $green.0 / 255.0, blue: $blue.0 / 255.0)"
    xml_content="$xml_content$separator    <color name=\"$id_lower\">#$hex</color>"
  done <"$csv_file"

  palette_class_name_camel=$(echo "$palette_class_name" | awk 'BEGIN{FS="_";OFS=""} {for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print}')
  palette_class_name_kebab=$(echo "$palette_class_name" | tr '_' '-')

  awk -v palette_content="$css_content" \
    '{gsub(/\s*\/\*content\*\//,palette_content); print}' \
    'templates/template.css' >"$output_dir/$palette_class_name_kebab.css"

  awk -v palette_content="$dart_content" \
    -v palette_class_name="$palette_class_name_camel" \
    '{gsub(/ClassName/,palette_class_name) gsub(/\s*\/\/content/,palette_content); print}' \
    'templates/template.dart' >"$output_dir/$palette_class_name.dart"

  awk -v palette_content="$gpl_content" \
    -v palette_name="$palette_name" \
    -v palette_url="$palette_url" \
    '{gsub(/#name/,palette_name) gsub(/#url/,palette_url) gsub(/#content/,palette_content); print}' \
    'templates/template.gpl' >"$output_dir/$palette_short_name.gpl"

  awk -v palette_content="$scss_content" \
    '{gsub(/\/\/content/,palette_content); print}' \
    'templates/template.scss' >"$output_dir/$palette_class_name_kebab.scss"

  awk -v palette_content="$swift_content" \
    '{gsub(/\s*\/\/content/,palette_content); print}' \
    'templates/template.swift' >"$output_dir/Color+Extensions.swift"

  awk -v palette_content="$xml_content" \
    '{gsub(/\s*<!--content-->/,palette_content); print}' \
    'templates/template.xml' >"$output_dir/colors.xml"
}

build_palette essential-color-palette.csv output/essential 'Kwezal Essential Color Palette' Kwezal_Essential essential_colors 'https://kwezal.com/essential-color-palette'
